inherit_gem:
  salsify_rubocop: conf/rubocop.yml

AllCops:
  TargetRubyVersion: 2.7
  Exclude:
    - 'gemfiles/*'
    - 'vendor/**/*'

Metrics/LineLength:
  Enabled: true
  Max: 120
  IgnoreCopDirectives: true
  IgnoredPatterns:
    - ^#

Style/FrozenStringLiteralComment:
  Enabled: true
