language: ruby
sudo: false
gemfile:
  - gemfiles/rails_4.2.gemfile
  - gemfiles/rails_5.0.gemfile
  - gemfiles/rails_5.1.gemfile
  - gemfiles/rails_5.2.gemfile
  - gemfiles/rails_6.0.gemfile
rvm:
  - 2.6.3
  - 2.5.5
  - 2.4.6
script:
  - bundle exec rubocop
  - bundle exec rspec
matrix:
  exclude:
  - rvm: 2.4.6
    gemfile: gemfiles/rails_6.0.gemfile
