version: 2.1
jobs:
  lint:
    docker:
      - image: salsify/ruby_ci:2.5.8
    working_directory: ~/rails-multitenant
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-gems-ruby-2.5.8-{{ checksum "rails_multitenant.gemspec" }}-{{ checksum "Gemfile" }}
            - v1-gems-ruby-2.5.8-
      - run:
          name: Install Gems
          command: |
            if ! bundle check --path=vendor/bundle; then
              bundle install --path=vendor/bundle --jobs=4 --retry=3
              bundle clean
            fi
      - save_cache:
          key: v1-gems-ruby-2.5.8-{{ checksum "rails_multitenant.gemspec" }}-{{ checksum "Gemfile" }}
          paths:
            - "vendor/bundle"
            - "gemfiles/vendor/bundle"
      - run:
          name: Run Rubocop
          command: bundle exec rubocop .rubocop.yml
  test:
    parameters:
      gemfile:
        type: string
      ruby_version:
        type: string
    docker:
      - image: salsify/ruby_ci:<< parameters.ruby_version >>
    environment:
      CIRCLE_TEST_REPORTS: "test-results"
      BUNDLE_GEMFILE: << parameters.gemfile >>
    working_directory: ~/rails-multitenant
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-gems-ruby-<< parameters.ruby_version >>-{{ checksum "rails_multitenant.gemspec" }}-{{ checksum "<< parameters.gemfile >>" }}
            - v1-gems-ruby-<< parameters.ruby_version >>-
      - run:
          name: Install Gems
          command: |
            if ! bundle check --path=vendor/bundle; then
              bundle install --path=vendor/bundle --jobs=4 --retry=3
              bundle clean
            fi
      - save_cache:
          key: v1-gems-ruby-<< parameters.ruby_version >>-{{ checksum "rails_multitenant.gemspec" }}-{{ checksum "<< parameters.gemfile >>" }}
          paths:
            - "vendor/bundle"
            - "gemfiles/vendor/bundle"
      - run:
          name: Run Tests
          command: |
            bundle exec rspec --format RspecJunitFormatter --out $CIRCLE_TEST_REPORTS/rspec/junit.xml --format progress spec
      - store_test_results:
          path: "test-results"
workflows:
  build:
    jobs:
      - lint
      - test:
          matrix:
            parameters:
              gemfile:
              - "gemfiles/rails_4.2.gemfile"
              - "gemfiles/rails_5.0.gemfile"
              - "gemfiles/rails_5.1.gemfile"
              - "gemfiles/rails_5.2.gemfile"
              - "gemfiles/rails_6.0.gemfile"
              - "gemfiles/rails_6.1.gemfile"
              ruby_version:
              - "2.5.8"
              - "2.6.6"
              - "2.7.2"
              - "3.0.0"
            exclude:
              - gemfile: "gemfiles/rails_4.2.gemfile"
                ruby_version: "2.7.2"
              - gemfile: "gemfiles/rails_4.2.gemfile"
                ruby_version: "3.0.0"
              - gemfile: "gemfiles/rails_5.0.gemfile"
                ruby_version: "3.0.0"
              - gemfile: "gemfiles/rails_5.1.gemfile"
                ruby_version: "3.0.0"
              - gemfile: "gemfiles/rails_5.2.gemfile"
                ruby_version: "3.0.0"
              - gemfile: "gemfiles/rails_6.0.gemfile"
                ruby_version: "3.0.0"
